version: "3.5"

services:
  app_dev:
    container_name: app_dev
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/home/python/app_dev
    networks:
      - rinha_de_backend
    depends_on:
      - postgres_dev

  postgres_dev:
    container_name: postgres_dev
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpassword
      POSTGRES_DB: rinha_de_backend_dev
    networks:
      - rinha_de_backend

networks:
  rinha_de_backend:
    driver: bridge
