version: "3.5"

services:
  api01: &api
    build: .
    container_name: api01
    hostname: api01
    environment:
      - FLASK_APP=rinha_de_backend_2024_q1/main/app:create_app('production')
      - SQLALCHEMY_DATABASE_URI=postgresql://superuser:superpassword@db/rinha_de_backend
    ports:
      - 8081:3000
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.43"
          memory: "200MB"

  api02:
    <<: *api
    container_name: api02
    hostname: api02
    ports:
      - 8082:3000

  nginx:
    container_name: nginx
    image: nginx:1.26.0
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"

  db:
    container_name: db
    hostname: db
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=superuser
      - POSTGRES_PASSWORD=superpassword
      - POSTGRES_DB=rinha_de_backend
    deploy:
      resources:
        limits:
          cpus: "0.47"
          memory: "140MB"

networks:
  default:
    driver: bridge
    name: rinha_de_backend
