version: "3.5"

services:
  app_dev:
    container_name: app_dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      FLASK_APP: rinha_de_backend_2024_q1/main/app:create_app('development')
    ports:
      - 5000:5000
    volumes:
      - .:/home/python/app_dev
    depends_on:
      - postgres_dev
      - postgres_test

  postgres_dev:
    container_name: postgres_dev
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpassword
      POSTGRES_DB: rinha_de_backend_dev

  postgres_test:
    container_name: postgres_test
    image: postgres:15-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpassword
      POSTGRES_DB: rinha_de_backend_test

networks:
  default:
    driver: bridge
    name: rinha_de_backend
