[default]
TITLE = "rinha_de_backend_2024_q1"
EXTENSIONS = [
    "rinha_de_backend_2024_q1.extensions.database", # must be the first ext to be executed
    "rinha_de_backend_2024_q1.extensions.migrate", # must be declared after database ext
    "rinha_de_backend_2024_q1.blueprints.cli",
    "rinha_de_backend_2024_q1.blueprints.router"
]

[development]
SQLALCHEMY_DATABASE_URI = "postgresql://superuser:superpassword@127.0.0.1:5432/rinha_de_backend"
